version: "3"
services:
  app:
    build: .
    environment:
      - DB_HOST=pg
      - SECRET_KEY_BASE="DEV-H}pwuJz;}Xe/C-!+C.X}jF[kz93,?tCJFM(FghytP@(<V)XL!.J@w<UeJ/,P-kgeKJ.:n){o4b9:p]bd^HTn3Jsc:c*j,}>(mX&!Lfk#kznmw\{U?mjXbvp@VTEC"
      - DB_USERNAME=postgres
      - DB_PASSWORD="DEV-_^+3{,ewt{_bgA@X!;(p,;na-}4x9h*Y"
      - DB_DATABASE=decidim_quickstart
      - RAILS_ENV=production
      - PORT=3000
      - RAILS_MAX_THREAD=5
      - RAILS_FORCE_SSL=false
      - RAILS_SERVE_STATIC_FILES=false
    ports:
      - 3000:3000
    depends_on:
      - pg
      - mailer
    networks:
      - private
      - default

  pg:
    image: postgres:11
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="DEV-_^+3{,ewt{_bgA@X!;(p,;na-}4x9h*Y"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=decidim_quickstart
    networks:
      - private

  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1025:1025"
      - "1080:80"
    networks:
      - private
      - default

volumes:
  node_modules: {}
  pg-data: {}
networks:
  private:
    internal: true